# Generated by Django 5.0.6 on 2024-05-25 09:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_seat_is_fire_exit_flight_airline_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="user",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="ticket_price",
        ),
        migrations.RemoveField(
            model_name="seat",
            name="is_confirmed",
        ),
        migrations.AddField(
            model_name="booking",
            name="age",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="booking",
            name="contact_details",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="booking",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="booking",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="selected_seats",
            field=models.CharField(default=dict, max_length=100),
        ),
        migrations.AddField(
            model_name="flight",
            name="arrival_time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="flight",
            name="departure_time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="flight",
            name="duration",
            field=models.DurationField(default=None),
        ),
        migrations.AddField(
            model_name="flight",
            name="flight_number",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="flight",
            name="price",
            field=models.DecimalField(decimal_places=2, default=190.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="seat",
            name="is_fire_exit",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="booking",
            name="seats",
            field=models.ManyToManyField(related_name="bookings", to="api.seat"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="flight",
            name="airline",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="flight",
            name="departure_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="seat",
            name="seat_class",
            field=models.CharField(
                choices=[
                    ("first", "First Class"),
                    ("business", "Business Class"),
                    ("economy", "Economy Class"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="seat",
            name="seat_number",
            field=models.CharField(max_length=4),
        ),
    ]
