# Generated by Django 5.0.6 on 2024-05-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_booking_user_remove_flight_ticket_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seat",
            name="flight",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="airline",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="flight_number",
        ),
        migrations.AlterField(
            model_name="flight",
            name="arrival_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="flight",
            name="departure_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="flight",
            name="duration",
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name="flight",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name="Booking",
        ),
        migrations.DeleteModel(
            name="Seat",
        ),
    ]
