# Generated by Django 5.0.6 on 2024-05-25 20:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_seat_flight_remove_flight_airline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="airline",
            field=models.CharField(default="Default Airline", max_length=100),
        ),
        migrations.AddField(
            model_name="flight",
            name="flight_number",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="flight",
            name="arrival_time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="flight",
            name="departure_time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="flight",
            name="duration",
            field=models.DurationField(default=None),
        ),
        migrations.AlterField(
            model_name="flight",
            name="price",
            field=models.DecimalField(decimal_places=2, default=190.0, max_digits=10),
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.CharField(max_length=4)),
                (
                    "seat_class",
                    models.CharField(
                        choices=[
                            ("first", "First Class"),
                            ("business", "Business Class"),
                            ("economy", "Economy Class"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_booked", models.BooleanField(default=False)),
                ("is_fire_exit", models.BooleanField(default=False)),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="api.flight",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(default="", max_length=100)),
                ("age", models.PositiveIntegerField(default=0)),
                ("email", models.EmailField(default="", max_length=254)),
                ("contact_details", models.CharField(default="", max_length=200)),
                ("selected_seats", models.CharField(default=dict, max_length=100)),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="api.flight",
                    ),
                ),
                (
                    "seats",
                    models.ManyToManyField(related_name="bookings", to="api.seat"),
                ),
            ],
        ),
    ]
