# Generated by Django 5.0.6 on 2024-05-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_flight_airline_flight_flight_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seat",
            name="flight",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="arrival_time",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="departure_time",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="price",
        ),
        migrations.AlterField(
            model_name="flight",
            name="airline",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="flight",
            name="duration",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="flight",
            name="flight_number",
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name="Booking",
        ),
        migrations.DeleteModel(
            name="Seat",
        ),
    ]
